### ISSUE TITLE
NPE after logging out -> logging in -> clicking event

### ISSUE THREAD

**Issue by kevinhinterlong** [HackIllinois/android-2017#123]
When the user logs out, we clear the local preferences/caches which is where we store the mapping of

`locationId` -> `locationName`

so if the user logs out, immediately logs back in, and then tries to click on an event for more details this mapping is not created.

Fortunately the crash forces the application to be restarted which solves the issue, but we could just fetch it where it's needed instead of relying on `SharedPreferences`

**Comment by kevinhinterlong** [comment]
Here's a log of this

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'org.hackillinois.android.api.response.location.LocationResponse$Location[] org.hackillinois.android.api.response.location.LocationResponse.getLocations()' on a null object reference
	at org.hackillinois.android.ui.modules.event.EventButtonItem.bindViewHolder(EventButtonItem.java:49)
	at org.hackillinois.android.ui.modules.event.EventButtonItem.bindViewHolder(EventButtonItem.java:21)
	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1723)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
	...
```
