### ISSUE TITLE
Primary colors must be opaque

### ISSUE THREAD

**Issue by kevinhinterlong** [HackIllinois/android-2017#125]
It looks like we've also had some issues with this, see [here](https://stackoverflow.com/a/29166908)

Here's a log of it

```java
FATAL EXCEPTION: main
Process: org.hackillinois.androidapp, PID: 16488
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.hackillinois.androidapp/org.hackillinois.android.ui.SplashActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:536)
	at android.app.Activity.onApplyThemeResource(Activity.java:3735)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
	at android.support.v7.app.e.setTheme(Unknown Source)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2349)
	... 10 more
```

**Comment by dl-eric** [comment]
Is this due to incompatible Android versions?

**Comment by kevinhinterlong** [comment]
It seems to affect mostly ~5.0-6.0 devices. I'm surprised I've never heard of this before though. We might have to just settle on an opaque color which basically matches the current one

**Comment by kevinhinterlong** [comment]
According to the browser dev tools color picker the color is `#514186` which looks basically the same on my phone so I'm going with that
